### ISSUE TITLE
Getting npm ERR at the time of installing dependencies while running sample apps

### ISSUE THREAD

**Issue by SaurabhhB** [AikidoSec/firewall-node#271]
Ran this command `npm i` from this path `/firewall-node/sample-apps/express-mysql` and received the below error:

```
$ npm i
npm ERR! Cannot set properties of null (setting 'dev')

npm ERR! A complete log of this run can be found in: C:\Users\saura\AppData\Local\npm-cache\_logs\2024-07-08T11_19_06_028Z-debug-0.log
```
![image](https://github.com/AikidoSec/firewall-node/assets/24986354/a0d055f5-d76b-42ea-907e-f4da7a24577d)

**Comment by hansott** [comment]
Hi @SaurabhhB, the error is because of a bug in the npm workspaces feature.

If you run `npm install --workspaces` in the root, it should work.

However, if you just want to test firewall out: It's easier to install the firewall in one of your own projects and avoiding the sample apps until we found an alternative for npm workspaces.

Hope this helps!
